package analizador;

import models.*;
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

parser code
{:
public static boolean automatas_generados = false;
public String id_conjunto;
public String id_expresion;
public static ArrayList<Excepcion> erroresSintacticos = new ArrayList<Excepcion>();

    public void syntax_error(Symbol s){
        //System.out.println("Error sintáctico recuperable en la linea "+ (s.left+1) + " Columna " + (s.right+1) + ". Token: " + s.value);
        Excepcion nuevo_error = new Excepcion("Sintáctico R", (String) s.value, (s.left+1), (s.right+1));
        erroresSintacticos.add(nuevo_error);
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        //System.out.println("Error sintáctico no recuperable en la linea "+ (s.left+1) + " Columna " + (s.right+1) + ". Token: " + s.value);
        Excepcion nuevo_error = new Excepcion("Sintáctico NR", (String) s.value, (s.left+1), (s.right+1));
        erroresSintacticos.add(nuevo_error);
    }

    //funcion para verificar si el conjunto existe o no
    //!MODIFICAAAAAAAAAAAAAAAAAAAAAAAAAAAAR!
    private boolean existeConj(String id) {
        Iterator<classConj> iteradorConj = ManipuladorData.listConj.iterator();
        while (iteradorConj.hasNext()) {
            classConj actualConj = iteradorConj.next();
            if (actualConj.getId().equals(id)) {
                return true;
            }
        }
        return false;
    }

    public int posER(String id) {
        int pos = 0;
        Iterator<classER> iteradorER = ManipuladorData.listER.iterator();
        while (iteradorER.hasNext()) {
            classER actualER = iteradorER.next();
            if (actualER.getId().equals(id)) {
                break;
            }
            pos++;
        }
        return pos;
    }

    private int posConj(String id) {
        int pos = 0;
        Iterator<classConj> iteradorConj = ManipuladorData.listConj.iterator();
        while (iteradorConj.hasNext()) {
            classConj actualConj = iteradorConj.next();
            if (actualConj.getId().equals(id)) {
                break;
            }
            pos++;
        }
        return pos;
    }
:}

terminal String MENOR_QUE,MAYOR_QUE,ADMIRACION,DIAGONAL,LLAVE_IZQUIERDA,LLAVE_DERECHA;
terminal String PORCENTAJE,PUNTO_COMA,DOS_PUNTOS,PUNTO,MENOS,COMA,INTERROGACION;
terminal String SUMA,ASTERISCO,TILDE,BARRA_VERTICAL;
terminal String RESERVADA_CONJUNTO,SALTO_LINEA,COMILLAS, COMILLA_SIMPLE,COMILLA_DOBLE;
terminal String NUMERO,NUMERO_DECIMAL,LETRA,IDENTIFICADOR,CARACTER_ESPECIAL, CARACTER, CADENA;


non terminal INICIAR;
non terminal INSTRUCCIONES;
non terminal CONJUNTOS;
non terminal CONJUNTO;
non terminal NOTACION;
non terminal CONJUNTO_NUMEROS;
non terminal CONJUNTO_LETRAS;
non terminal CONJUNTO_CARACTERES_ESPECIALES;
non terminal EXPRESIONES;
non terminal EXPRESION;
non terminal DEFINICION_EXPR;
non terminal LEXEMAS;
non terminal LEXEMA;
non terminal IDENTIFICADOR_CONJUNTO;
non terminal IDENTIFICADOR_EXPRESION;
non terminal PUNTO_ER;
non terminal BARRA_VERTICAL_ER;
non terminal ASTERISCO_ER;
non terminal SUMA_ER;
non terminal INTERROGACION_ER;
//non terminal CONTENIDO_COMILLA_ER;

//falta
//calcular conjuntos

start with INICIAR;

INICIAR ::= LLAVE_IZQUIERDA INSTRUCCIONES LLAVE_DERECHA;

INSTRUCCIONES ::= CONJUNTOS EXPRESIONES PORCENTAJE PORCENTAJE PORCENTAJE PORCENTAJE LEXEMAS;

CONJUNTOS ::= CONJUNTO CONJUNTOS
    | CONJUNTO;

CONJUNTO ::= RESERVADA_CONJUNTO DOS_PUNTOS IDENTIFICADOR_CONJUNTO MENOS MAYOR_QUE NOTACION PUNTO_COMA
{:
    id_conjunto = "";
:}
;

IDENTIFICADOR_CONJUNTO ::= IDENTIFICADOR:a
{:
    //!CAMBIARRRR!
    if(!existeConj(a)){
        ManipuladorData.listConj.add(new classConj(a));
        id_conjunto = a;
    }
:}
;

NOTACION ::= LETRA:a TILDE LETRA:b
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
        char inicio = ManipuladorData.listConj.get(posConj(id_conjunto)).getStart();
        char fin = b.charAt(0);
        for (int i = (int) inicio + 1; i < (int) fin + 1; i++){
            ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(Character.toString((char) i));
        }       
    :}
    |NUMERO:a TILDE NUMERO:b
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
        int inicio = Integer.parseInt(ManipuladorData.listConj.get(posConj(id_conjunto)).getStringStart());
        int fin = Integer.parseInt(b);
        for (int i = inicio + 1; i < fin + 1; i++){
            ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(Integer.toString(i));
        }       
    :}
    |CARACTER_ESPECIAL:a TILDE CARACTER_ESPECIAL:b
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
        char inicio = ManipuladorData.listConj.get(posConj(id_conjunto)).getStart();
        char fin = b.charAt(0);
        for (int i = (int) inicio + 1; i < (int) fin + 1; i++){
            ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(Character.toString((char) i));
        }       
    :}
    |CONJUNTO_NUMEROS
    |CONJUNTO_LETRAS
    |CONJUNTO_CARACTERES_ESPECIALES
    ;

CONJUNTO_NUMEROS ::= NUMERO:a COMA CONJUNTO_NUMEROS
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
    :}
    |NUMERO:a
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
    :}
    ;

CONJUNTO_LETRAS ::= LETRA:a COMA CONJUNTO_LETRAS
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
    :}
    |LETRA:a
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
    :}
    ;

CONJUNTO_CARACTERES_ESPECIALES ::= CARACTER_ESPECIAL:a COMA CONJUNTO_CARACTERES_ESPECIALES
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
    :}
    |CARACTER_ESPECIAL:a
    {:
        ManipuladorData.listConj.get(posConj(id_conjunto)).getConjunto().add(a);
    :}
    ;

EXPRESIONES ::= EXPRESION EXPRESIONES
    |EXPRESION
    ;

EXPRESION ::= IDENTIFICADOR_EXPRESION MENOS MAYOR_QUE DEFINICION_EXPR PUNTO_COMA:a
{:
    ManipuladorData.listER.get(posER(id_expresion)).getArbolExpresion().idAceptacion();
    ManipuladorData.listER.get(posER(id_expresion)).getArbolExpresion().calculos();
    ManipuladorData.listER.get(posER(id_expresion)).crearTablaSiguientes();
    ManipuladorData.listER.get(posER(id_expresion)).crearTablaEstados();
    try{
        ManipuladorData.listER.get(posER(id_expresion)).getArbolExpresion().graficarArbol(ManipuladorData.listER.get(posER(id_expresion)).getNumDocumentos());
        ManipuladorData.listER.get(posER(id_expresion)).graficarTablaSiguientes();
        ManipuladorData.listER.get(posER(id_expresion)).graficarTablaEstados();
        ManipuladorData.listER.get(posER(id_expresion)).graficarAFD();
        automatas_generados = true;

    }catch (IOException e){
        //puede cambiar
         e.printStackTrace();
    }
:}
;

IDENTIFICADOR_EXPRESION ::= IDENTIFICADOR:a 
{:
    //cambiar A
    id_expresion = a;
    ManipuladorData.listER.add(new classER(a,""+ManipuladorData.conteo_Expresiones+ManipuladorData.conteoAnalisis));
    //verificar su funcionamiento ya que es static
    ManipuladorData.conteo_Expresiones += 1;
:};

DEFINICION_EXPR ::= PUNTO_ER DEFINICION_EXPR DEFINICION_EXPR
    | BARRA_VERTICAL_ER DEFINICION_EXPR DEFINICION_EXPR
    | ASTERISCO_ER DEFINICION_EXPR
    | SUMA_ER DEFINICION_EXPR
    | INTERROGACION_ER DEFINICION_EXPR
    | CARACTER:a
    {:
        String no_comillas = a.replace("\"","");
        ManipuladorData.listER.get(posER(id_expresion)).insertNodo("valor", no_comillas);
        System.out.println(a);
    :}
    | LLAVE_IZQUIERDA IDENTIFICADOR:a LLAVE_DERECHA
    {:
        ManipuladorData.listER.get(posER(id_expresion)).insertNodo("valor", a);
        System.out.println(a);
    :}
    ;

PUNTO_ER ::= PUNTO:a
{:
    ManipuladorData.listER.get(posER(id_expresion)).insertNodo("operacion", a);
    System.out.println(a);
:}
;

BARRA_VERTICAL_ER ::= BARRA_VERTICAL:a
{:
    ManipuladorData.listER.get(posER(id_expresion)).insertNodo("operacion", a);
    System.out.println(a);
:}
;

ASTERISCO_ER ::= ASTERISCO:a
{:
    ManipuladorData.listER.get(posER(id_expresion)).insertNodo("cerradura", a);
    System.out.println(a);
:}
;

SUMA_ER ::= SUMA:a
{:
    ManipuladorData.listER.get(posER(id_expresion)).insertNodo("cerradura", a);
    System.out.println(a);
:}
;

INTERROGACION_ER ::= INTERROGACION:a
{:
    ManipuladorData.listER.get(posER(id_expresion)).insertNodo("cerradura", a);
    System.out.println(a);
:}
;

LEXEMAS ::= LEXEMA LEXEMAS
    |LEXEMA;

LEXEMA ::= IDENTIFICADOR DOS_PUNTOS CADENA PUNTO_COMA
    ;