
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLA_SIMPLE = 20;
  public static final int MENOS = 12;
  public static final int INTERROGACION = 14;
  public static final int PUNTO = 11;
  public static final int PALABRAS = 23;
  public static final int LETRA = 22;
  public static final int SUMA = 15;
  public static final int MAYOR_QUE = 3;
  public static final int NUMERO_DECIMAL = 28;
  public static final int NUMERO_ENTERO = 27;
  public static final int TILDE = 17;
  public static final int DOS_PUNTOS = 10;
  public static final int PORCENTAJE = 8;
  public static final int COMA = 13;
  public static final int MENOR_QUE = 2;
  public static final int VARIAS_LETRAS = 25;
  public static final int COMILLA_DOBLE = 21;
  public static final int LLAVE_IZQUIERDA = 6;
  public static final int RESERVADA_CONJUNTO = 19;
  public static final int EOF = 0;
  public static final int ASTERISCO = 16;
  public static final int ADMIRACION = 4;
  public static final int error = 1;
  public static final int DIAGONAL = 5;
  public static final int IDENTIFICADOR = 24;
  public static final int LLAVE_DERECHA = 7;
  public static final int PUNTO_COMA = 9;
  public static final int BARRA_VERTICAL = 18;
  public static final int VARIOS_NUMEROS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_QUE",
  "MAYOR_QUE",
  "ADMIRACION",
  "DIAGONAL",
  "LLAVE_IZQUIERDA",
  "LLAVE_DERECHA",
  "PORCENTAJE",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "PUNTO",
  "MENOS",
  "COMA",
  "INTERROGACION",
  "SUMA",
  "ASTERISCO",
  "TILDE",
  "BARRA_VERTICAL",
  "RESERVADA_CONJUNTO",
  "COMILLA_SIMPLE",
  "COMILLA_DOBLE",
  "LETRA",
  "PALABRAS",
  "IDENTIFICADOR",
  "VARIAS_LETRAS",
  "VARIOS_NUMEROS",
  "NUMERO_ENTERO",
  "NUMERO_DECIMAL"
  };
}

